<?php

require_once('PHPUnit/Extensions/AppiumTestCase.php');
require_once('PHPUnit/Extensions/AppiumTestCase/Element.php');

class Test extends PHPUnit_Extensions_AppiumTestCase
{
    public static $browsers;

    public function __construct($name = NULL, array $data = array(), $dataName = '', $configuration)
    {
        Test::$browsers = $configuration;
        parent::__construct($name, $data, $dataName);
    }

    public function removeApp($appId)
    {
        parent::removeApp($appId); // TODO: Change the autogenerated stub
    }

    public function installApp($path)
    {
        parent::installApp($path); // TODO: Change the autogenerated stub
    }

    public function testStuff()
    {
        $this->removeApp('com.openclassrooms.com');
        /*
        $element = $this->byAccessibilityId('Element on screen');

        $this->assertInstanceOf('PHPUnit_Extensions_AppiumTestCase_Element', $element);
    */}
}